### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by jmandel** [dfontana/adventofcode#43]
Love the clean and elegant solution. I'm missing the purpose of this one line:

https://github.com/dfontana/adventofcode/blob/be8ed00643d09f0b9512a73320c80a96e22f2137/y2021/src/solutions/day4.rs#L126

**Comment by dfontana** [comment]
> Love the clean and elegant solution. I'm missing the purpose of this one line:
> 
> https://github.com/dfontana/adventofcode/blob/be8ed00643d09f0b9512a73320c80a96e22f2137/y2021/src/solutions/day4.rs#L126

Ha! Nice spot. My original solve initialized that structure differently, and I must've carried it over recklessly
